apiVersion: v1
kind: Pod
metadata:
  name: pyodbc-demo-pod
  namespace: workload-demo
spec:
  containers:
  - name: pyodbc-demo-container    
    image: moimhossain/python-odbc-azure-sql:v1        
    imagePullPolicy: Always
    volumeMounts:
    - name: sa-token
      mountPath: /var/run/secrets/tokens
    env:
    - name: AZ_TENANT_ID
      value: "XXXX"
    - name: AZ_CLIENT_ID
      value: "XXXX"
    - name: AZ_SERVER
      value: "tcp:XXXXX.database.windows.net,1433"
    - name: AZ_DATABASE
      value: "XXXX"    
  serviceAccountName: workload-demo-service-account
  volumes:
  - name: sa-token
    projected:
      sources:
      - serviceAccountToken:
          path: sa-token
          expirationSeconds: 1000          
