apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 79a29925-0345-4f05-946f-d869ad41f9e1
  name: workload-demo-service-account
  namespace: workload-demo